### ISSUE TITLE
practica2 unidad4 acceso de datos

### ISSUE THREAD

**Issue by ang3-l32** [SistemasTecTlaxiaco/practica-de-visualizacion-de-datos-topicos4semestre2022#1]
[topicos unidad 4  actividad 2practica acceso de datos.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-visualizacion-de-datos-topicos4semestre2022/files/8895919/topicos.unidad.4.actividad.2practica.acceso.de.datos.pdf)

**Comment by RaelRGB** [comment]
18.5

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
